logging:
    level:
        org:
            springframework:
                ws: TRACE
management:
    endpoint:
        health:
            enabled: true
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 5000
spring:
    security:
        user:
            name: admin
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: '@spring.profiles.active@'
multitenancy:
    mtapp:
        master:
            datasource:
                url: jdbc:postgresql://db.experiment.extreme.com.co:5432/xtenant?useSSL=false
                username: test
                password: 3xtr3m3s3rv3r
                driverClassName: org.postgresql.Driver
                connectionTimeout: 20000
                maxPoolSize: 250
                idleTimeout: 300000
                minIdle: 5